project:
  type: website
  title: "Observatoire de la vulnérabilité aux inondations Vienne - Clain"

website:
  back-to-top-navigation: true
  #title: "Observatoire de la vulnérabilité <br> aux inondations Vienne - Clain"
  navbar:
     search: false
     logo: Images/logo_porteurs_projet_transparent.png
     collapse-below: xxl
     tools-collapse: false
     right:
        - href: index.qmd
          text: Accueil
  #        icon: house
          
        - href: mieux_comprendre.qmd
          text: Les inondations
        #- sidebar:Objectifs
        
        - text: Objectif n°1
          menu:
           - text: "Objectif n°1 : Augmenter la sécurité des populations"
           - href: batiments_plain_pied.qmd
             text: Bâtiments plain-pied
             
        - text: Objectif n°2
          menu:
           - text: "Objectif n°2 : Stabiliser/réduire le coût des dommages"
           - href: dommages_entreprises.qmd
             text: Dommages aux entreprises
             
        - text: Objectif n°3
          menu:
           - text: "Objectif n°3 : Raccourcir le délai de retour à la normale"
           - href: habitants_zones_inondables.qmd
             text: Nombre et proportion d'habitants en zone inondable 
            
        - text: Â propos
          menu:
          - text: EPTB-vienne.fr
            href: https://www.eptb-vienne.fr
            target: _blank
        
     tools: 
         - href: https://fr.linkedin.com/company/eptb-vienne
           aria-label: LinkedIn
           icon: linkedin
           text: LinkedIn
         - text: Nous contacter
           href: https://eptb-vienne.fr/contact
           icon: envelope
           
  page-footer:
    left: "Site créé avec [Quarto](https://quarto.org/)"
    center: "©CEREMA"
    background: light
    right: 
      - icon: linkedin
        href: https://fr.linkedin.com/company/cerema
      - icon: twitter-x 
        href: https://x.com/ceremacom
      - icon: youtube
        href: https://www.youtube.com/@cerema3139
          
           
  # sidebar:
  #    - id: Objectifs
  #      title: "Objectifs"
  #      style: "docked"
  #      search: true
  #      background: light
  #      collapse-level: 2
  #      contents: 
  #        - section: "Objectif n°1"
  #          contents:         
  #        - text: Description de l'objectif n°1
  #          href: objectif1.qmd
  #        - text: Bâtiments de plain-pied
  #          href: batiments_plain_pied.qmd
           
  
  #      - text: Objectif n°1:Augmenter la sécurité des populations
  #        href: objectif1.qmd
  #      - text: ▼
  #        menu:
  #        - text: Bâtiments de plain-pied
  # sidebar:
  #   style: "docked"  # ou "docked" pour qu’elle reste fixée
  #   contents:
  #       - text: "Accueil"
  #         href: index.qmd
  #       - href: mieux_comprendre.qmd
  #         text: "Comprendre les inondations"
  #       - text: "Â propos"
  #        menu:
  #        - text: EPTB-vienne.fr
  #          href: https://www.eptb-vienne.fr
  #          target: _blank
        
format:
  html:
    theme: [flatly, custom.scss]
    #css: custom.scss
    toc: true
    toc-title: Sur cette page
    toc-location: right
    toc-depth: 2
    link-external-newwindow: true
    include-in-header: assets/inject-script.html
    #include-after-body: assets/logo.html
    

editor: visual

